/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as GameHistoryIndexImport } from './routes/game-history/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GameHistoryIndexRoute = GameHistoryIndexImport.update({
  id: '/game-history/',
  path: '/game-history/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/game-history/': {
      id: '/game-history/'
      path: '/game-history'
      fullPath: '/game-history'
      preLoaderRoute: typeof GameHistoryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game-history': typeof GameHistoryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game-history': typeof GameHistoryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/game-history/': typeof GameHistoryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game-history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game-history'
  id: '__root__' | '/' | '/game-history/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameHistoryIndexRoute: typeof GameHistoryIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameHistoryIndexRoute: GameHistoryIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/game-history/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/game-history/": {
      "filePath": "game-history/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
